gardener/diki

- pkg/kubernetes/config/etcd.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r8/242380.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r8/242380_test.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r8/242426.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r8/242426_test.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r8/242432.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r8/242432_test.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r8/242433.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r8/242433_test.go
This PR improves `ETCD` peer options rules `242380`, `242426`, `242432` and `242433` by skipping them when ETCD runs as a single instance, since they are not used in that case.
Fixes #
```feature user
`ETCD` peer options rules `242380`, `242426`, `242432` and `242433` are now skipped when `ETCD` runs as a single instance.
```
> Improve `ETCD` peer options rules

- pkg/provider/gardener/ruleset/disak8sstig/v1r8/242393.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r8/242393_test.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r8/242394.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r8/242394_test.go
This PR fixes rules `242393` and `242394`.
Rule `242393` when passed always reported with `SSH daemon inactive (or could not be probed)`, now it should report with `SSH daemon service not installed` when the `systemctl is-active sshd` command outputs `inactive`.
Rule `242394` returned errored status in cases it should have passed. Rule `242394` now correctly passes.
Fixes #
```bugfix user
A bug causing rule `242393` to pass with wrong message was fixed.
```
```bugfix user
A bug causing rule `242394` to error when it should pass was fixed.
```
> Fix `ssh` rules

- hack/gen-new-disak8sstig-version.sh
- pkg/provider/gardener/ruleset/disak8sstig/v1r8_ruleset.go
Added script to generate new DISA k8s STIGs dir and `ruleset` file. The dir and file are generated by using the same components from an existing version.
Example use:
`./hack/gen-new-disak8sstig-version.sh v1r8 v1r10`
Part of #9
```feature developer
NONE
```
> Add script to generate new `DISA k8s STIGs` dir and ruleset file

- example/config/gardener.yaml
- pkg/kubernetes/utils/utils.go
- pkg/kubernetes/utils/utils_test.go
- pkg/provider/gardener/internal/utils/utils.go
- pkg/provider/gardener/internal/utils/utils_test.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r8/242414.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r8/242414_test.go
This PR changes rule `242414` to use pod and namespace label selectors for accepting pods instead of pod name and namespace prefixes.
Fixes #
```other user
Selecting accepted pods for rule `242414` in the config file has been changed to use pod and namespace label selectors instead of name prefixes.
```
> Use label selector instead of name prefix for rule `242414`

- pkg/report/templates/html/merged_report.html
- pkg/report/templates/html/report.html
This PR lowers the size of html reports by removing unnecessary new lines and white spaces.
Fixes #
```feature user
NONE
```
> Shrink `html` reports

- pkg/provider/gardener/ruleset/disak8sstig/v1r10/node_files_permissions_and_owner.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r8/node_files_permissions_and_owner.go
This PR changes the Name of `node-files` rule.
Fixes #
```feature user
NONE
```
> Fix `node-files` rule Name

- pkg/provider/gardener/ruleset/disak8sstig/ruleset.go
Fixes #
```feature user
Diki can now run DISA Kubernetes STIG version `v1r10` ruleset.
```
> Add `v1r10` to `FromGenericConfig`

- .github/workflows/upload-diki-binaries.yaml
This PR adds a github workflow action `diki-uploader` which uploads binaries to new releases. 
Fixes #
```feature user
NONE
```
> Add `diki-uploader` workflow action

- pkg/report/templates/html/merged_report.html
- pkg/report/templates/html/report.html
This PR lowers the size of `html` reports by removing overused font spans.
Fixes #
```feature user
NONE
```
> Shrink size of `html` reports

- pkg/report/merged_report.go
- pkg/report/render.go
- pkg/report/report.go
- pkg/report/templates/html/merged_report.html
- pkg/report/templates/html/report.html
Sorts the metadata keys and providers in order to generate more consistent reports.
Fixes #
```feature user
Metadata and providers are now sorted when generating a report in order to improve consistency and readability.
```
> Improve provider meta sorting

- pkg/kubernetes/pod/pod.go
Fixes #
```other user
Error messages when encountering pod timeouts while waiting for the pod to reach healthy state were improved.
```
> Improve `waitPodHealthy` error message

- pkg/provider/gardener/ruleset/disak8sstig/v1r10/pod_files_permissions_and_owner.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r10/pod_files_permissions_and_owner_test.go
Fixes #
```other user
DISA Kubernetes STIGS `pod-files` rule now checks only files with paths part of the `volumeMounts` for the specific container. It also excludes directories of no interest like `/var/log/journal`.
```
> `pod-files` checks only files with paths part of the `volumeMounts` of the container

- pkg/report/templates/html/merged_report.html
- pkg/report/templates/html/report.html
This PR fixes new lines in `html` templates by using `-` and removes some unnecessary formatting.
Fixes #
```feature user
NONE
```
> Fix new lines in `html` templates

- pkg/kubernetes/pod/pod.go
When bash commands error they sometimes output an error message on stderr, exit with an exit code or do both. This PR changes the `SimplePodExecutor` `Execute` method to return the stderr first, if there is one, since it is more  descriptive.
Fixes #
```feature user
NONE
```
> `SimplePodExecutor` `Execute()` return `stderr` before error code

- pkg/provider/gardener/internal/utils/utils.go
- pkg/provider/gardener/internal/utils/utils_test.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r10/pod_files_permissions_and_owner.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r10/pod_files_permissions_and_owner_test.go
Fixes #
```bugfix| user
DISA Kubernetes STIGs `pod-files` rule now creates `diki` pods only on nodes with free allocatable space.
```
> Create `diki` pods only on nodes with free allocatable pod space for `pod-files` rule

- example/config/gardener.yaml
- pkg/provider/gardener/ruleset/disak8sstig/v1r10/options.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r10/pod_files_permissions_and_owner.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r10/pod_files_permissions_and_owner_test.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r10_ruleset.go
This PR adds a new option `expectedFileOwner` to DISA Kubernetes STIGS `pod-files` rule which allows the user to select which `users `and `groups` are expected in the config file. The options defaults to expecting only ID `0` for `users` and `groups`
Fixes #
```feature user
Added new option `expectedFileOwner` to DISA Kubernetes STIGS `pod-files` rule which allows the user to select which `users `and `groups` are expected. The options defaults to expecting only ID `0` for `users` and `groups`.
```
> Add `expectedFileOwner` option to `pod-files` rule

- pkg/provider/gardener/ruleset/disak8sstig/v1r10/pod_files_permissions_and_owner.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r10/pod_files_permissions_and_owner_test.go
Fixes #
```other user
NONE
```
> Always return all check results for `pod-files` rule

- pkg/provider/gardener/ruleset/disak8sstig/v1r10/242442.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r10/242442_test.go
Fixes #
```other user
DISA Kubernetes STIGs `242442` rule no longer checks shoot pods that are not managed by Gardener.
```
> [Kubernetes STIG v1r10] 242442: check only Gardener managed pods in shoot

- pkg/provider/gardener/internal/utils/utils.go
- pkg/provider/gardener/internal/utils/utils_test.go
Add `GetSingleAllocatableNodePerWorker()` to internal utils, which is an improved version of `GetSingleRunningNodePerWorker()`. `GetSingleAllocatableNodePerWorker()` also checks if the node has at least 1 allocatable spot.
Fixes #
```feature user
NONE
```
> Add GetSingleAllocatableNodePerWorker function to internal utils

- pkg/provider/gardener/ruleset/disak8sstig/v1r10/242442.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r10/242442_test.go
Fixes #
```feature user
NONE
```
> [Kubernetes STIG v1r10] 242442: use imageID instead of image name for comparison

- pkg/provider/gardener/ruleset/disak8sstig/v1r10/242387.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r10/242387_test.go
Currently `Kubelet` rules create a pod on the first `Ready` node found for a worker group. The first node might not have allocatable spots and the rule would return an error. This PR fixes the problem for rule 242387 by always using a node with allocatable spots or if there is none such node for a worker group the rule returns a warning.
If this PR is approved PRs with the same changes for the other `Kubelet` rules will be opened.
Fixes #
```feature user
NONE
```
> [Kubernetes STIG v1r10] 242387:  create pods only on nodes with allocatable spot

- pkg/provider/gardener/ruleset/disak8sstig/v1r10/242387_test.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r10/242391.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r10/242391_test.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r10/242392.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r10/242392_test.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r10/242397.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r10/242397_test.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r10/242399.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r10/242399_test.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r10/242404.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r10/242404_test.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r10/242420.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r10/242420_test.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r10/242424.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r10/242424_test.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r10/242425.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r10/242425_test.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r10/242434.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r10/242434_test.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r10/245541.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r10/245541_test.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r10/254801.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r10/254801_test.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r10/node_files_permissions_and_owner.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r10/node_files_permissions_and_owner_test.go
Create pods only on nodes with allocatable spots for all Kubelet rules, as in #57.
Fixes #
```bugfix user
DISA Kubernetes STIGs Kubelet rules now creates `diki` pods only on nodes with free allocatable space.
```
> [Kubernetes STIG v1r10] Kubelet rules: create pods only on nodes with allocatable spots

- example/config/gardener.yaml
- pkg/provider/gardener/ruleset/disak8sstig/v1r10/242414.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r10/242415.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r10/242415_test.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r10/options.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r10_ruleset.go
Fixes #
```feature user
Added new option `acceptedPods` to DISA Kubernetes STIGS `242415` rule which allows the user to configure environment variables for selected pods to be accepted.
```
```bugfix user
A bug causing rule `242414` to crash when no options for the rule were set was fixed.
```
> [Kubernetes STIG v1r10] 242415 rule: add new option to select pods to accept

- pkg/provider/gardener/ruleset/disak8sstig/v1r10/pod_files_permissions_and_owner.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r10/pod_files_permissions_and_owner_test.go
This PR improves the *.key files checks required from `242467` rule in `pod-files` rule. *.key files in mandatory components are required to have max privilege of `640`. We do not enforce `600` because k8s does not provide a way to easily change the owner of a file and containers are expected to run as nonroot.
Fixes #
```bugfix user
DISA Kubernetes STIGs `pod-files` rule now expects `0640` permission setting for `*.key` files of mandatory components. This change improves the `242467` rule which requires `0600` permissions for such files. `0600` is not enforced since k8s does not provide an easy way to change the owner of a file and containers are expected to …
```
> [Kubernetes STIG v1r10] pod-files rule: add check for 242467 rule

- pkg/provider/gardener/provider.go
- pkg/provider/gardener/ruleset/disak8sstig/ruleset.go
- pkg/provider/virtualgarden/provider.go
- pkg/provider/virtualgarden/ruleset/disak8sstig/ruleset.go
- pkg/shared/provider/provider.go
- pkg/shared/ruleset/ruleset.go
We can reuse some implementations across providers and rulesets.
Fixes #
```feature user
NONE
```
> Reuse implementations across providers and rulesets

- pkg/provider/gardener/internal/utils/utils.go
- pkg/provider/gardener/internal/utils/utils_test.go
Added new `MatchFileOwnersCases()` function to internal utils that will be used to check file owners in the new split rules from `node-files` and `pod-files`. The old `MatchFilePermissionsAndOwnersCases` will not be used in the new rules and will be removed with the removal of the `node-file` and `pod-file` rules.
Fixes #
```feature user
NONE
```
> Add MatchFileOwnersCases() to internal utils

- .ci/pipeline_definitions
- Dockerfile
This PR adds `diki-ops` image to be used for diki pods and adds it to the pipeline definition file. 
Fixes #
```other dependency
Upgraded diki base image: gcr.io/distroless/static-debian11 -> gcr.io/distroless/static-debian12
```
> Create custom diki-ops image definition

- pkg/provider/gardener/ruleset/disak8sstig/v1r11/pod_files_permissions_and_owner.go
This PR fixes a typo in pod-files rule
Fixes #
```feature user
NONE
```
> [DISA K8s STIG] Fix typo in pod-files rule

- .ci/pipeline_definitions
GCR has been deprecated [0] in favour of Artifact-Registry.
Thus, change push-targets for OCI-Images:
- europe-docker.pkg.dev/gardener-project/snapshots for snapshots
- europe-docker.pkg.dev/gardener-project/releases for releases
- europe-docker.pkg.dev/gardener-project/public for combined view of snapshots + releases
[0]
https://cloud.google.com/artifact-registry/docs/transition/transition-from-gcr
Fixes #
```other developer
Change OCI Image Registry from GCR (`eu.gcr.io/gardener-project`) to Artifact-Registry (`europe-docker.pkg.dev/gardener-project/releases`). Users should update their references.
```
> Switch GCR -> Artifact-Registry

- pkg/internal/utils/utils.go
- pkg/internal/utils/utils_test.go
This PR adds `GetPodMountedFileStatResults()` to be used in the split `pod-files` DISA K8s STIGs rules.
Fixes #
```feature user
NONE
```
> Add GetPodMountedFileStatResults utils func

- pkg/internal/utils/utils.go
- pkg/internal/utils/utils_test.go
- pkg/provider/gardener/internal/utils/utils.go
- pkg/provider/gardener/internal/utils/utils_test.go
This PR moves `ExceedFilePermissions()` from  `pkg/provider/gardener/internal/utils` to `pkg/internal/utils`
Fixes #
```feature user
NONE
```
> Move ExceedFilePermissions() to diki internal utils

- Makefile
- imagevector/images.yaml
- pkg/provider/gardener/ruleset/constants.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r11/242387.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r11/242391.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r11/242392.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r11/242393.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r11/242394.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r11/242397.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r11/242399.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r11/242404.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r11/242420.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r11/242424.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r11/242425.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r11/242434.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r11/245541.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r11/254801.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r11/node_files_permissions_and_owner.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r11/pod_files_permissions_and_owner.go
- pkg/shared/images/images.go
- pkg/shared/ruleset/disak8sstig/v1r11/242459.go
This PR replaces the use of the `ops-toolbelt` image with `diki-ops` for DISA K8s STIG V1R11 ruleset. The `diki-ops` is considerably lighter and contains only the needed tools for `diki`.
Fixes #
```feature user
Diki now uses a lighter image for pod executors in DISA K8s STIG V1R11 ruleset
```
> [DISA K8s STIG] Use diki-ops image for pod executor

- pkg/internal/utils/utils.go
- pkg/internal/utils/utils_test.go
- pkg/provider/gardener/internal/utils/utils.go
- pkg/provider/gardener/internal/utils/utils_test.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r11/node_files_permissions_and_owner.go
This PR moves `MatchFileOwnersCases` to `pkg/internal/utils` and also improves it by using `FileStats` as parameter.
Fixes #
```feature user
NONE
```
> Move MatchFileOwnersCases to pkg/internal/utils

- pkg/kubernetes/utils/utils.go
- pkg/kubernetes/utils/utils_test.go
This PR adds `GetReplicaSets()` and `GetDeploymentPods()` functions to `pkg/kubernetes/utils`.
`GetReplicaSets()` return all replicaSets for a given namespace.
`GetDeploymentPods()` returns all pods of a specified deployment by finding the deployments replicaSets and then the pods that reference the found replicaSets.
Fixes #
```feature user
NONE
```
> Add GetDeploymentPods kubernetes utils function

- pkg/provider/gardener/internal/utils/utils.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r11/node_files_permissions_and_owner.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r11_ruleset.go
- pkg/shared/ruleset/disak8sstig/v1r11/242459.go
This PR renames the use of package `pkg/internal/utils` from `dikiutils` to `intutils` and utilizes the use of shared rule ids in `pkg/provider/gardener/ruleset/disak8sstig/v1r11_ruleset.go`
Fixes #
```feature user
NONE
```
> Clean up package usage

- pkg/shared/ruleset/disak8sstig/v1r11/242459.go
- pkg/shared/ruleset/disak8sstig/v1r11/242459_test.go
This PR improves rule 242459 by not continuing the for loop when `GetMountedFilesStats` errors. When `GetMountedFilesStats` errors it also returns all successfully found file stats.
Fixes #
```feature user
NONE
```
> [DISA K8s STIG] 242459 check files even if GetMountedFilesStats errored

- pkg/internal/utils/utils.go
- pkg/internal/utils/utils_test.go
This PR improved getContainerMountedFileStatResults by adding error message when it fails to find file source.
Fixes #
```feature user
NONE
```
> Return error when getContainerMountedFileStatResults fails to find file source

- .reuse/dep5
- LICENSE
- LICENSES/Apache-2.0.txt
- LICENSES/CC-BY-4.0.txt
- LICENSES/MIT.txt
- README.md
- SECURITY.md
* Created/Updated `LICENSE` file
* Deleted `SECURITY.md` file. It is centrally managed
* Created/Updated `.reuse/dep5` file
* Created/Updated `LICENSES` folder
* Added badge for reuse compliance in `README.md` file
> Make repo compliant

- pkg/internal/utils/utils.go
- pkg/internal/utils/utils_test.go
This PR improves the getContainerMountedFileStatResults() utils func to error when a dir has files, but they could not be found by the `find` command
Fixes #
```feature user
NONE
```
> Improve getContainerMountedFileStatResults() dir files not found error.

- example/config/managedk8s.yaml
- pkg/provider/managedk8s/ruleset/disak8sstig/v1r11/242414.go
- pkg/provider/managedk8s/ruleset/disak8sstig/v1r11/242414_test.go
- pkg/provider/managedk8s/ruleset/disak8sstig/v1r11/options.go
- pkg/provider/managedk8s/ruleset/disak8sstig/v1r11_ruleset.go
This PR implement DISA K8s STIGs rule 242414 for the managedk8s provider.
Part of #67
```feature user
NONEO
```
> [DISA K8s STIG] Implement rule 242414

- pkg/shared/ruleset/disak8sstig/v1r11/242459.go
- pkg/shared/ruleset/disak8sstig/v1r11/242459_test.go
This PR changes rule 242459 from DISA K8s STIG to expect maximum `0640` permissions instead of `0600`.
Fixes #
```feature user
Rule 242459 from DISA K8s STIG  was revisited to expect maximum `0640` permissions instead of `0600`.
```
> [DISA K8s STIG] Change rule 242459 to check for 0640 permissions

- example/config/managedk8s.yaml
- pkg/provider/managedk8s/ruleset/disak8sstig/v1r11/242442.go
- pkg/provider/managedk8s/ruleset/disak8sstig/v1r11/242442_test.go
- pkg/provider/managedk8s/ruleset/disak8sstig/v1r11/options.go
- pkg/provider/managedk8s/ruleset/disak8sstig/v1r11_ruleset.go
This PR implement DISA K8s STIGs rule 242442 for the managedk8s provider.
Part of #67 
```feature user
NONE
```
> [DISA K8s STIG] Implement rule 242442

- example/config/virtualgarden.yaml
- pkg/provider/builder/virtualgarden.go
- pkg/provider/virtualgarden/options.go
- pkg/provider/virtualgarden/provider.go
- pkg/provider/virtualgarden/ruleset/disak8sstig/options.go
- pkg/provider/virtualgarden/ruleset/disak8sstig/ruleset.go
- pkg/provider/virtualgarden/ruleset/disak8sstig/v1r11_ruleset.go
This PR removes unnecessary kubeconfig requirement from virtual garden provider.
Fixes #169
```bugfix user
Virtual Garden provider no longer requires garden kubeconfig to execute rulesets.
```
> Remove unnecessary kubeconfig from virtual garden provider

- README.md
- cmd/diki/app/app.go
- example/config/gardener.yaml
- example/config/managedk8s.yaml
- example/config/virtualgarden.yaml
- pkg/config/config.go
Fixes #
```breaking user
Setting `output.path` in the diki configuration file is now deprecated. Users are advised to use the `--output` flag instead.
```
```feature user
The `diki run` command now accepts an `--output` flag. If set diki will write a report summary to the file path location.
```
> Add output flag to diki run

- pkg/report/templates/html/merged_report.html
This PR hides metadata of assessed instances of merged reports in collapse elements. The change will help in cases where a great number of reports are used to create a merge report and their metadata fills the html page.
Fixes #
```feature user
NONE
```
> Hide metadata of assessed instances in collapse element

- docs/usage/partial-disa-k8s-stig-shoot.md
- example/config/managedk8s.yaml
- example/guides/partial-disa-k8s-stig-shoot.yaml
This PR adds documentation on how to run Managed K8S ruleset on a Gardener shoot cluster.
Fixes #174 
```feature user
NONE
```
> [Docu] How to run Managed K8S ruleset on a Gardener shoot cluster

- docs/usage/partial-disa-k8s-stig-shoot.md
This PR adds better explanation to when to use the `managedk8s` provider against a shoot cluster in the `partial-disa-k8s-stig-shoot` documentation.
Fixes #
```feature user
NONE
```
> [Docu] Improve partial-disa-k8s-stig-shoot documentation

- .reuse/dep5
- README.md
- cmd/diki/app/app.go
- pkg/report/difference.go
- pkg/report/difference_test.go
- pkg/report/render.go
- pkg/report/templates/html/difference_report.html
- pkg/report/templates/html/merged_report.html
- pkg/report/templates/html/report.html
This PR adds a new `diki report generate diff` command that creates a html difference report with 1 or more json difference reports. The `--identity-attributes` is required, it's value is a list of `key=value` pairs, where the keys are the IDs for the providers that will be present in the generated difference report and the values are metadata attributes to be used as IDs.
Fixes #159 
```feature user
A new command `diki report generate diff` that converts one or more `json` difference reports into a single `html` difference report was introduced.
```
> Add generate diff command to create html difference reports

- .ci/pipeline_definitions
Remove [redundant component-descriptor trait](https://github.com/gardener/diki/blob/687f28218b3f3844b4f0edbbb398526d38e2ab44/.ci/pipeline_definitions#L44) to properly release new diki versions to Google Artifact Registry.
This duplicate configuration was introduced with [this commit](https://github.com/gardener/diki/commit/609ef65dadf05015eec5fc58ffa9fbe225a38e5a#diff-f6d7f429b1dea52fac85480a4d09b40a781726c59a82705f6e7b2af33972b2cbR56).
Fixes #
```breaking operator
Release new diki versions to europe-docker.pkg.dev/gardener-project/releases
```
> Rm redundant component-descriptor trait

- pkg/provider/managedk8s/ruleset/disak8sstig/v1r11/242451.go
This PR fixes a bug causing rule 242451 validation for managedk8s provider to crash when no file owner options for the rule were set.
Fixes #
```bugfix user
A bug causing rule 242451 validation for managedk8s provider to crash when no file owner options for the rule were set was fixed.
```
> [DISA K8s STIG] Fix rule 242451 validation for managed k8s provider

- pkg/provider/managedk8s/ruleset/disak8sstig/v1r11/242451.go
Cherry pick of #204 on release-v0.6.
#204: [DISA K8s STIG] Fix rule 242451 validation for managed k8s provider
**Release Notes:**
```bugfix user
A bug causing rule 242451 validation for managedk8s provider to crash when no file owner options for the rule were set was fixed.
```
> [release-v0.6] Automated cherry pick of #204: [DISA K8s STIG] Fix rule 242451 validation for managed k8s provider

- pkg/report/report.go
This PR adds additional metadata to generated json Diki report. The new metadata is `dikiVersion`, which contains the release version of Diki.
Fixes #
```feature user
The generated `json` report summary now contains a `dikiVersion` containing the release version of `Diki`.
```
> Add diki release version to generated json report

- example/config/gardener.yaml
- example/config/managedk8s.yaml
- example/config/virtualgarden.yaml
- pkg/kubernetes/pod/pod.go
- pkg/kubernetes/pod/pod_test.go
- pkg/provider/builder/gardener.go
- pkg/provider/builder/managedk8s.go
- pkg/provider/builder/virtualgarden.go
- pkg/provider/gardener/options.go
- pkg/provider/gardener/provider.go
- pkg/provider/gardener/ruleset/disak8sstig/options.go
- pkg/provider/gardener/ruleset/disak8sstig/ruleset.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r11_ruleset.go
- pkg/provider/managedk8s/options.go
- pkg/provider/managedk8s/provider.go
- pkg/provider/managedk8s/ruleset/disak8sstig/options.go
- pkg/provider/managedk8s/ruleset/disak8sstig/ruleset.go
- pkg/provider/managedk8s/ruleset/disak8sstig/v1r11/242466.go
- pkg/provider/managedk8s/ruleset/disak8sstig/v1r11_ruleset.go
- pkg/provider/virtualgarden/options.go
- pkg/provider/virtualgarden/provider.go
- pkg/provider/virtualgarden/ruleset/disak8sstig/options.go
- pkg/provider/virtualgarden/ruleset/disak8sstig/ruleset.go
- pkg/provider/virtualgarden/ruleset/disak8sstig/v1r11_ruleset.go
This PR add the option to users to add their own labels to diki pods for the `gardener`, `managedk8s` and `virtual` provider. Diki pod specific labels cannot be overwritten. Users can add their labels by setting the `args` field `opsPodLabels` with their wanted labels.
Fixes #
```feature user
A new field `.args.additionalOpsPodLabels` has been added to the `gardener`, `managedk8s` and `virtual` providers. The field contains key value pairs that will be added to the `diki` ops pods as additional labels.
```
> Add `args` field `opsPodLabels` to all providers

- cmd/diki/app/app.go
This PR improves the writing of html reports by truncating the target dir.
Fixes #
```bugfix user
A bug causing generated `html` reports to not truncate target path has been fixed.
```
> Fix diki html report truncate

- .ci/pipeline_definitions
This PR adds CVE categorisation for both `diki` and `diki-ops` images
Fixes #
```feature user
NONE
```
> Add cve categorisation for diki images

- cmd/diki/app/app.go
Fixes #
```feature user
The `report generate` command now accepts a `--format` flag which determines the output format of the generated report. It can be set to one of `html` or `json`. Defaults to `html`.
```
> Add `format` flag to `report generate` command

- pkg/internal/utils/utils.go
This PR fixes a bug causing rules to Error with "could not find files in foo" when there were no regular files. This bug was caused due to using the `ls` command to search for any not checked files. The `ls` command also returns special files and directories which caused the function to error when there were no regular files.
Fixes #
```feature user
A bug causing rules that check files on nodes to error with `could not find files in foo` when there were no regular files in `foo` was fixed.
```
> Fix bug causing rules to Error with "could not find files in foo"

- pkg/provider/managedk8s/ruleset/disak8sstig/v1r11/242442.go
- pkg/provider/managedk8s/ruleset/disak8sstig/v1r11/242442_test.go
- pkg/shared/ruleset/disak8sstig/v1r11/242447.go
- pkg/shared/ruleset/disak8sstig/v1r11/242447_test.go
- pkg/shared/ruleset/disak8sstig/v1r11/242448.go
- pkg/shared/ruleset/disak8sstig/v1r11/242448_test.go
This PR improved `kube-proxy` rules by making them return `Errored` check result when the `kube-proxy` pod cannot be found. `Errored` suits this case better since the rule could not be checked, hence it cannot be `Failed`.
Fixes #
```other user
Rules that cannot find `kube-proxy` pod now return `Errored` check result.
```
> Return Errored check result when kube-proxy pod cannot be found

- example/config/managedk8s.yaml
- example/config/virtualgarden.yaml
- pkg/provider/gardener/ruleset/disak8sstig/options.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r11_ruleset.go
- pkg/provider/managedk8s/ruleset/disak8sstig/options.go
- pkg/provider/managedk8s/ruleset/disak8sstig/ruleset.go
- pkg/provider/managedk8s/ruleset/disak8sstig/v1r11_ruleset.go
- pkg/provider/virtualgarden/ruleset/disak8sstig/options.go
- pkg/provider/virtualgarden/ruleset/disak8sstig/ruleset.go
- pkg/provider/virtualgarden/ruleset/disak8sstig/v1r11_ruleset.go
- pkg/shared/ruleset/disak8sstig/retryerrors/retryerrors.go
- pkg/shared/ruleset/disak8sstig/retryerrors/retryerrors_test.go
This PR adds retry logic to rules in the `managedk8s` and `virtualgarden` providers `disa-kubernetes-stig` ruleset. It adds them in a similar way to #257 
Part of #253 
```feature user
The `disa-kubernetes-stig` ruleset rules for `virtualgarden` and `managedk8s` providers can now be retried if their results contain a known `Errored` message.
```
```feature user
The `disa-kubernetes-stig` ruleset config for `virtualgarden` and `managedk8s` providers has been enhanced with `maxRetries` setting, which sets the number of maximum retries for rule runs. Defaults to 1.
```
> Retry rules that Error with known messages for managedk8s and virtualgarden providers

- pkg/provider/gardener/ruleset/disak8sstig/v1r11/242451.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r11/242451_test.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r11/242466.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r11/242466_test.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r11/242467.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r11/242467_test.go
- pkg/provider/managedk8s/ruleset/disak8sstig/v1r11/242451.go
- pkg/provider/managedk8s/ruleset/disak8sstig/v1r11/242451_test.go
- pkg/provider/managedk8s/ruleset/disak8sstig/v1r11/242466.go
- pkg/provider/managedk8s/ruleset/disak8sstig/v1r11/242466_test.go
- pkg/provider/managedk8s/ruleset/disak8sstig/v1r11/242467.go
- pkg/provider/managedk8s/ruleset/disak8sstig/v1r11/242467_test.go
- pkg/provider/virtualgarden/ruleset/disak8sstig/v1r11/242451.go
- pkg/provider/virtualgarden/ruleset/disak8sstig/v1r11/242451_test.go
- pkg/provider/virtualgarden/ruleset/disak8sstig/v1r11/242466.go
- pkg/provider/virtualgarden/ruleset/disak8sstig/v1r11/242466_test.go
- pkg/provider/virtualgarden/ruleset/disak8sstig/v1r11/242467.go
- pkg/provider/virtualgarden/ruleset/disak8sstig/v1r11/242467_test.go
- pkg/shared/ruleset/disak8sstig/v1r11/242445.go
- pkg/shared/ruleset/disak8sstig/v1r11/242445_test.go
- pkg/shared/ruleset/disak8sstig/v1r11/242446.go
- pkg/shared/ruleset/disak8sstig/v1r11/242446_test.go
- pkg/shared/ruleset/disak8sstig/v1r11/242459.go
- pkg/shared/ruleset/disak8sstig/v1r11/242459_test.go
- pkg/shared/ruleset/disak8sstig/v1r11/242460.go
- pkg/shared/ruleset/disak8sstig/v1r11/242460_test.go
`Errored` suits this case better since the rule could not be checked, hence it cannot be `Failed`.
Fixes #
```other user
Rules that cannot find specific pod now return `Errored` check result.
```
> Return Errored check result when pod cannot be found

- pkg/internal/utils/utils.go
- pkg/internal/utils/utils_test.go
This PR updates `ExceedFilePermissions()`'s comment to correctly present how the function works
Fixes #
```feature user
NONE
```
> Fix ExceedFilePermissions internal funcion's comment

- pkg/report/difference.go
- pkg/report/merged_report.go
- pkg/report/render.go
- pkg/report/report.go
- pkg/report/templates/html/difference_report.html
- pkg/report/templates/html/merged_report.html
- pkg/report/templates/html/report.html
- pkg/rule/rule.go
- pkg/rule/rule_test.go
This PR adds glossary to all `html` reports which contains the meanings of rule check statuses.
Fixes #269 
```feature user
Glossary has been added to html reports that explains rule statuses.
```
> Add glossary to html reports

- example/config/gardener.yaml
- example/config/managedk8s.yaml
- pkg/provider/gardener/ruleset/disak8sstig/v1r11/242400.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r11/242400_test.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r11/242451.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r11/242451_test.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r11/242466.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r11/242466_test.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r11/242467.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r11/242467_test.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r11/options.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r11_ruleset.go
- pkg/provider/managedk8s/ruleset/disak8sstig/v1r11/242400.go
- pkg/provider/managedk8s/ruleset/disak8sstig/v1r11/242400_test.go
- pkg/provider/managedk8s/ruleset/disak8sstig/v1r11/242451.go
- pkg/provider/managedk8s/ruleset/disak8sstig/v1r11/242451_test.go
- pkg/provider/managedk8s/ruleset/disak8sstig/v1r11/242466.go
- pkg/provider/managedk8s/ruleset/disak8sstig/v1r11/242466_test.go
- pkg/provider/managedk8s/ruleset/disak8sstig/v1r11/242467.go
- pkg/provider/managedk8s/ruleset/disak8sstig/v1r11/242467_test.go
- pkg/shared/ruleset/disak8sstig/option/options.go
This PR add a new rule option `kubeProxyDisabled` to rules that check the `kube-proxy` while checking other components as well. When the `kubeProxyDisabled` is set to `true` the `kube-proxy` check will be skipped.
This change is needed since a cluster can work without `kube-proxy` and adding the option will provide a way for rules that check not only the `kube-proxy` to skip only the `kube-proxy` check.
Fixes #
```feature user
A new rule option `kubeProxyDisabled` is added to rules that check many components, which contain the `kube-proxy`. Setting this option to `true` would skip only the `kube-proxy` check in the rule. Defaults to `true`.
```
> [DISA K8s STIG] Add kubeProxyDisabled option to rules

- pkg/provider/gardener/ruleset/disak8sstig/v1r11_ruleset.go
- pkg/provider/gardener/ruleset/disak8sstig/v2r1_ruleset.go
- pkg/provider/managedk8s/ruleset/disak8sstig/v1r11_ruleset.go
- pkg/provider/managedk8s/ruleset/disak8sstig/v2r1_ruleset.go
- pkg/provider/virtualgarden/ruleset/disak8sstig/v1r11_ruleset.go
- pkg/provider/virtualgarden/ruleset/disak8sstig/v2r1_ruleset.go
This PR changes all instances of `rule` to `rule_id` in log messages.
Fixes #290 
cc @AleksandarSavchev 
```other user
Log messages now consistently use `rule_id` instead of both `rule_id` and `rule` to identify the rule.
```
> Improve consistency in log messages 

- cmd/diki/app/app.go
This PR updates the constructor of the ProviderResult struct when initialized (in the case we have both ruleset-id and ruleset-version flags specified) by adding the missing metadata field from the provider in question that is used for the ruleset run.
Fixes #296 
NONE
```bugfix user
A bug causing generated summary reports to not contain `provider.metadata`, when `--ruleset-id` and `--ruleset-version` flags are set, was fixed.
```
> Generated summary reports should contain provider metadata

- example/config/managedk8s.yaml
- example/guides/partial-disa-k8s-stig-shoot.yaml
- pkg/provider/gardener/ruleset/disak8sstig/rules/242414_test.go
- pkg/provider/gardener/ruleset/disak8sstig/rules/242415_test.go
- pkg/provider/gardener/ruleset/disak8sstig/v1r11_ruleset.go
- pkg/provider/gardener/ruleset/disak8sstig/v2r1_ruleset.go
- pkg/provider/managedk8s/ruleset/disak8sstig/rules/242414_test.go
- pkg/provider/managedk8s/ruleset/disak8sstig/rules/242415_test.go
- pkg/shared/ruleset/disak8sstig/option/options.go
- pkg/shared/ruleset/disak8sstig/option/options_test.go
- pkg/shared/ruleset/disak8sstig/rules/242383.go
- pkg/shared/ruleset/disak8sstig/rules/242383_test.go
- pkg/shared/ruleset/disak8sstig/rules/242417.go
- pkg/shared/ruleset/disak8sstig/rules/242417_test.go
This PR refactors the accepted pod structs implemented for rules #242414 and #242415 by aggregating the label matching options into a singular shared structure.
The accepted pod struct for #242417 is refactored to utilize the new structure and now can add exemptions from the ruleset checks by matching namespaces by labels.
The accepted pod struct for #242383 is refactored as well to use namespace labels for matching its rule exemptions.
Fixes #286
```breaking user
This change affects only the `managedk8s` provider. Configuration for DISA K8s STIG rules `242383` and `242417` now does not accept namespace names directly but rely on matching namespaces by labels. …
```
> Consistently use namespaceMatchLabels across rules

- pkg/internal/utils/utils.go
- pkg/internal/utils/utils_test.go
- pkg/kubernetes/utils/utils.go
- pkg/kubernetes/utils/utils_test.go
- pkg/provider/gardener/ruleset/disak8sstig/rules/242400.go
- pkg/provider/gardener/ruleset/disak8sstig/rules/242400_test.go
- pkg/provider/managedk8s/ruleset/disak8sstig/rules/242400.go
- pkg/provider/managedk8s/ruleset/disak8sstig/rules/242400_test.go
- pkg/shared/ruleset/disak8sstig/retryerrors/retryerrors_test.go
- pkg/shared/ruleset/disak8sstig/rules/242447.go
- pkg/shared/ruleset/disak8sstig/rules/242447_test.go
- pkg/shared/ruleset/disak8sstig/rules/242448.go
- pkg/shared/ruleset/disak8sstig/rules/242448_test.go
This PR modifies the GetContainerCommand and GetContainerID util functions to be variadic and accept more than one possible container name for matching. Along with those modifications, rules that utilize the functions (242400, 242447, 242448) are also modified to search for "proxy" containers if "kube-proxy" containers are absent. Additional unit tests are added to validate the new modification.
Fixes #314 
NONE
```bugfix user
A bug causing DISA Kubernetes STIG rules that check the `kube-proxy` container to fail to find the container, when the container name is `proxy`, was fixed.
```
> Check for proxy container if kube-proxy is not present

- .ci/pipeline_definitions
- .gitignore
- Makefile
- hack/sast.sh
- pkg/internal/stringgen/generator.go
Enable gosec for SAST scans
Fixes #331 
gosec changes are influenced from https://github.com/gardener/gardener-extension-shoot-oidc-service/pull/248
```other operator
`gosec` is made available for SAST(static application security testing), it can be run with `make sast` or `make sast-report`, but is also incorporated in the `verify` and `verify-extended` makefile targets. 
```
> Enable gosec for SAST scans

- pkg/report/report.go
Empty targets can be seen in reports.
```json
{
"targets": [
{}
]
}
```
With this change this should no longer be the case.
Fixes #
```bugfix user
A bug that was causing reports to sometimes include empty targets was fixed.
```
> Do not report empty targets

- docs/rulesets/security-hardened-k8s-cluster/ruleset.md
- docs/rulesets/security-hardened-k8s-cluster/security-hardened-k8s-cluster-v0.1.0.yaml
This PR adds documentation about the `Security Hardened Kubernetes Cluster` ruleset `v0.1.0`.
Fixes #
```feature user
NONE
```
> Add `Security Hardened Kubernetes Cluster` ruleset version `v0.1.0`

- .golangci.yaml
- pkg/provider/garden/ruleset/securityhardenedshoot/rules/2003.go
- pkg/provider/garden/ruleset/securityhardenedshoot/rules/2003_test.go
- pkg/provider/garden/ruleset/securityhardenedshoot/rules/rules_suite_test.go
- pkg/provider/garden/ruleset/securityhardenedshoot/v01_ruleset.go
Fixes #
```feature user
Implementation for rule `2003` from the `security-hardened-shoot-cluster` ruleset for provider `garden`.
```
> [Security Hardened Shoot Cluster] Rule 2003 implementation

- pkg/kubernetes/pod/privileged.go
- pkg/kubernetes/pod/privileged_test.go
This PR reduces the entered namespaces by `nsenter` to only the required namespace for `diki-ops` pod. This is done to avoid error resulted from not having permissions to enter a specific namespace.
It has been validated that diki works with only the mount `-m` namespace, if other namespaces are required in the future we can add them when they are needed.
Fixes #
```feature user
NONE
```
> Reduce entered namespaces by `nsenter`

- pkg/internal/utils/set.go
- pkg/internal/utils/set_test.go
- pkg/provider/virtualgarden/ruleset/disak8sstig/v1r11_ruleset.go
- pkg/provider/virtualgarden/ruleset/disak8sstig/v2r1_ruleset.go
- pkg/shared/ruleset/disak8sstig/rules/242382.go
- pkg/shared/ruleset/disak8sstig/rules/242382_test.go
With the introduction of [StructuredAuthorization](https://kubernetes.io/docs/reference/access-authn-authz/authorization/#configuring-the-api-server-using-an-authorization-config-file) when `authorization-mode` cannot be set when `authorization-config` is set. This PR improves DISA K8s STIG rule 242382 by also checking the specified `AuthoricationConfiguration` file.
Fixes #
```feature user
DISA K8s STIG rule 242382 now also checks `AuthorizationConfiguration` when it is set via `authorization-config`.
```
> Improve DISA K8s STIG rule 242382 to also check `AuthorizationConfiguration`

- pkg/provider/garden/ruleset/securityhardenedshoot/rules/2001.go
- pkg/provider/garden/ruleset/securityhardenedshoot/rules/2001_test.go
- pkg/provider/garden/ruleset/securityhardenedshoot/v01_ruleset.go
This PR implements rule 2001 of the Security Hardened Shoot Ruleset. It evaluates the SSH access field (based on it's value or availability) of the shoot spec.
Part of #304 
```feature user
Implementation for rule `2001` from the `security-hardened-shoot-cluster` ruleset for provider `garden`.
```
> Add Rule 2001 to Security Hardened Shoot Ruleset

- pkg/provider/garden/ruleset/securityhardenedshoot/rules/2001_test.go
- pkg/provider/garden/ruleset/securityhardenedshoot/rules/2002.go
- pkg/provider/garden/ruleset/securityhardenedshoot/rules/2002_test.go
- pkg/provider/garden/ruleset/securityhardenedshoot/rules/2003_test.go
- pkg/provider/garden/ruleset/securityhardenedshoot/v01_ruleset.go
This PR is an implementation of Rule 2002 of the Hardened Shoot Ruleset specification. It evaluates the following 5 kubernetes components: {kubeAPIServer,kubeControllerManager,kubeScheduler,kubeProxy,kubelet}, and checks for the featureGates.AllAlpha boolean flag in their specs.
Part of #304
```feature user
Implementation for rule `2002` from the `security-hardened-shoot-cluster` ruleset for provider `garden`.
```
> Add Rule 2002 to the Security Hardened Shoot Ruleset

- pkg/provider/garden/ruleset/securityhardenedshoot/rules/2000.go
- pkg/provider/garden/ruleset/securityhardenedshoot/rules/2000_test.go
- pkg/provider/garden/ruleset/securityhardenedshoot/v01_ruleset.go
This PR is an implementation of the Rule 2000 of the Security Hardened Shoot Cluster Ruleset. It retrieves metadata about the shoot cluster and evaluates the EnableAnonymousAuthentication flag (if present) of the Kube API Server component.
Part of #304 
```feature user
Implementation for rule `2000` from the `security-hardened-shoot-cluster` ruleset for provider `garden`.
```
> [Security Hardened Shoot Cluster] Rule 2000 Implementation

- pkg/kubernetes/pod/privileged.go
- pkg/kubernetes/pod/privileged_test.go
Fixes #
```other operator
Pods created by diki will be terminated 300 seconds after start.
```
> Lower diki pod lifetime to 300 seconds

- pkg/provider/garden/ruleset/securityhardenedshoot/rules/2006.go
- pkg/provider/garden/ruleset/securityhardenedshoot/rules/2006_test.go
- pkg/provider/garden/ruleset/securityhardenedshoot/v01_ruleset.go
This PR implements Rule 2006 for the Security Hardened Shoot Cluster Ruleset. It evaluates the EnableStaticTokenKubeconfig and the Kubernetes version in the Shoot Spec.
Part of #304 
```feature user
Implementation for rule `2006` from the `security-hardened-shoot-cluster` ruleset for provider `garden`.
```
> [Security Hardened Shoot Cluster] Rule 2006 Implementation

- docs/rulesets/security-hardened-k8s/ruleset.md
- example/config/managedk8s.yaml
- pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2001.go
- pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2001_test.go
- pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/options.go
- pkg/provider/managedk8s/ruleset/securityhardenedk8s/v01_ruleset.go
Part of https://github.com/gardener/diki/issues/356
```feature user
Implementation for rule `2001` from the `security-hardened-k8s` ruleset for provider `managedk8s`.
```
> [Security Hardened Kubernetes Cluster] Rule 2001 implementation

- pkg/kubernetes/utils/utils.go
- pkg/kubernetes/utils/utils_test.go
- pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2000.go
- pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2000_test.go
- pkg/provider/managedk8s/ruleset/securityhardenedk8s/v01_ruleset.go
Part of https://github.com/gardener/diki/issues/356
```feature user
Implementation for rule `2000` from the `security-hardened-k8s` ruleset for provider `managedk8s`.
```
> [Security Hardened Kubernetes Cluster] Rule 2000 implementation

- pkg/kubernetes/utils/utils.go
- pkg/kubernetes/utils/utils_test.go
Fixes #
```bugfix user
A bug causing some rules to error when they encounter a `Pod` without an `OwnerReference` has been fixed.
```
> Fix `GetDeploymentPods` utils function when pod does not have `OwnerReference`

- pkg/provider/garden/ruleset/securityhardenedshoot/rules/1000.go
- pkg/provider/garden/ruleset/securityhardenedshoot/rules/1000_test.go
This PR improves the implementation of rule 1000 by also checking the shoot labels if the extension type is enabled there.
Fixes #
```feature user
NONE
```
> [Security Hardened Shoot Cluster] Rule 1000 check Shoot labels

- example/config/managedk8s.yaml
- pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2003.go
- pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2003_test.go
- pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2008.go
- pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2008_test.go
This PR contains a modification to the acceptedResources handling in Rules 2003 and 2008 of the Security Hardened Kubernetes Ruleset by adding the option to accept all volumes in an accepted pod by using a wildcard. 
Fixes #407 
```feature user
Accepted volume names for rules 2003 and 2008 of the Security Hardened Kubernetes Ruleset can be generalized by using a wildcard in the configuration.
```
> Add a wildcard option for volumes contained in AcceptedPods for Rules 2003 and 2008

- cmd/diki/app/app.go
- pkg/report/report.go
- pkg/report/report_test.go
This PR adds an additional flag to the diki report generate command that specifies the minimal status of the checks that should be included in the rendered report. This flag only discards check results that have a higher status when generating a regular or merged report.
Fixes #378 
```feature user
`diki report generate` now has a --min-status flag that discards check results with a higher status than the argument.
```
> Add a minimal status option to the report generating command

- example/config/managedk8s.yaml
- example/guides/security-hardened-k8s-shoot.yaml
- pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2000.go
- pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2000_test.go
- pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/options.go
- pkg/provider/managedk8s/ruleset/securityhardenedk8s/v01_ruleset.go
This PR adds rule options to Rule `2000` from the `security-hardened-k8s`. The rule options allow specific namespaces to be accepted to have `Ingress` and/or `Egress` traffic allowed by default.
Fixes #
```feature user
Rule options have been added to Rule `2000` from the `security-hardened-k8s`.
```
> [Security Hardened Kubernetes Cluster] Rule 2000 add rule options

- docs/rulesets/security-hardened-shoot-cluster/ruleset.md
- docs/rulesets/security-hardened-shoot-cluster/security-hardened-shoot-cluster-v0.1.0.yaml
- docs/rulesets/security-hardened-shoot-cluster/security-hardened-shoot-cluster-v0.2.0.yaml
- example/config/garden.yaml
- pkg/provider/garden/ruleset/securityhardenedshoot/rules/1002.go
- pkg/provider/garden/ruleset/securityhardenedshoot/rules/1002_test.go
- pkg/provider/garden/ruleset/securityhardenedshoot/rules/options.go
- pkg/provider/garden/ruleset/securityhardenedshoot/ruleset.go
- pkg/provider/garden/ruleset/securityhardenedshoot/v01_ruleset.go
- pkg/provider/garden/ruleset/securityhardenedshoot/v02_ruleset.go
Fixes #430 
```feature user
Implementation for rule `1002` from the `security-hardened-shoot-cluster` ruleset for provider `garden`.
```
> [Security Hardened Shoot Cluster] Rule 1002 implementation

- .github/workflows/upload-diki-binaries.yaml
This PR adds update diki versions in homebrew tap and chocolatey repositories steps to the `upload_diki_binaries` github action.
Changes have been validated on forked repos. Generated example PRs:
https://github.com/AleksandarSavchev/homebrew-tap/pull/1
https://github.com/AleksandarSavchev/chocolatey-packages/pull/1
Fixes #
```feature user
NONE
```
> Update diki binaries in homebre tap and chocolatey

- docs/rulesets/security-hardened-k8s/ruleset.md
- pkg/internal/utils/utils.go
- pkg/internal/utils/utils_test.go
- pkg/provider/gardener/ruleset/disak8sstig/rules/242414.go
- pkg/provider/gardener/ruleset/disak8sstig/rules/242414_test.go
- pkg/provider/gardener/ruleset/disak8sstig/rules/242415.go
- pkg/provider/gardener/ruleset/disak8sstig/rules/242415_test.go
- pkg/provider/gardener/ruleset/disak8sstig/rules/242442.go
- pkg/provider/gardener/ruleset/disak8sstig/rules/242442_test.go
- pkg/provider/managedk8s/ruleset/disak8sstig/rules/242414.go
- pkg/provider/managedk8s/ruleset/disak8sstig/rules/242414_test.go
- pkg/provider/managedk8s/ruleset/disak8sstig/rules/242415.go
- pkg/provider/managedk8s/ruleset/disak8sstig/rules/242415_test.go
- pkg/provider/managedk8s/ruleset/disak8sstig/rules/242442.go
- pkg/provider/managedk8s/ruleset/disak8sstig/rules/242442_test.go
- pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2001.go
- pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2001_test.go
- pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2004.go
- pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2005.go
- pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2005_test.go
- pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2006.go
- pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2007.go
- pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2008.go
- pkg/provider/virtualgarden/ruleset/disak8sstig/rules/242442.go
- pkg/provider/virtualgarden/ruleset/disak8sstig/rules/242442_test.go
Fixes #426
```feature user
Multiple rules that check `Pod` containers from `.spec.containers` now also check containers from `.spec.initContainers`.
```
> Refactor rules that check `Pod` containers to also check containers in `initContainers`

- pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2005.go
- pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2005_test.go
Fixes #442 
```feature user
NONE
```
> [Security Hardened Kubernetes Cluster] Rule 2005 return errored checkResult when imageID is empty

- docs/rulesets/security-hardened-shoot-cluster/ruleset.md
- docs/rulesets/security-hardened-shoot-cluster/security-hardened-shoot-cluster-v0.2.0.yaml
- example/config/garden.yaml
- pkg/provider/garden/ruleset/securityhardenedshoot/rules/1001.go
- pkg/provider/garden/ruleset/securityhardenedshoot/rules/1001_test.go
- pkg/provider/garden/ruleset/securityhardenedshoot/rules/options.go
- pkg/provider/garden/ruleset/securityhardenedshoot/ruleset.go
- pkg/provider/garden/ruleset/securityhardenedshoot/v02_ruleset.go
This PR implements and registers rule 1001 of the `Security Hardened Shoot` ruleset for the `Garden` provider. The rule checks the shoot spec for it's Kubernetes version and evaluates it's support based on the `CloudProfile/NamespacedCloudProfile` in the project
Fixes #432 
```feature user
Implementation for rule `1001` from the `security-hardened-shoot-cluster` ruleset for provider `garden`.
```
> [Security Hardened Shoot Cluster] Rule 1001 Implementation

- docs/rulesets/security-hardened-shoot-cluster/ruleset.md
- docs/rulesets/security-hardened-shoot-cluster/security-hardened-shoot-cluster-v0.2.0.yaml
- go.mod
- go.sum
- pkg/provider/garden/ruleset/securityhardenedshoot/rules/1000.go
- pkg/provider/garden/ruleset/securityhardenedshoot/rules/1000_test.go
- pkg/provider/garden/ruleset/securityhardenedshoot/rules/1002.go
- pkg/provider/garden/ruleset/securityhardenedshoot/rules/1002_test.go
- pkg/provider/garden/ruleset/securityhardenedshoot/rules/1003.go
- pkg/provider/garden/ruleset/securityhardenedshoot/rules/1003_test.go
- pkg/provider/garden/ruleset/securityhardenedshoot/v02_ruleset.go
Fixes https://github.com/gardener/diki/issues/431
```feature user
Implementation for rule `1003` from the `security-hardened-shoot-cluster` ruleset for provider `garden`.
```
> [Security Hardened Shoot Cluster] Rule 1003 implementation

- docs/providers/garden.md
- docs/rulesets/security-hardened-shoot-cluster/ruleset.md
- docs/rulesets/security-hardened-shoot-cluster/security-hardened-shoot-cluster-v0.2.1.yaml
- example/config/garden.yaml
- example/guides/disa-k8s-stig-shoot.yaml
- pkg/provider/builder/garden.go
- pkg/provider/garden/provider.go
- pkg/provider/garden/ruleset/securityhardenedshoot/rules/1003.go
- pkg/provider/garden/ruleset/securityhardenedshoot/rules/1003_test.go
- pkg/provider/garden/ruleset/securityhardenedshoot/rules/options.go
- pkg/provider/garden/ruleset/securityhardenedshoot/ruleset.go
- pkg/provider/garden/ruleset/securityhardenedshoot/v02_ruleset.go
This PR improves rule 1003 for `security-hardened-shoot-cluster` ruleset by also checking if extension Lakom is configured with `Cluster` scope in order to validate all images in cluster.
Fixes #
```feature user
Rule `1003` from the `security-hardened-shoot-cluster` ruleset for provider `garden` now checks if the Lakom extension is enabled, starting from version `v0.2.1`.
```
```feature user
Rule `1003` from the `security-hardened-shoot-cluster` ruleset for provider `garden` now can be configured with an allowed list of Lakom scopes., starting from version `v0.2.1`.
```
> [Security Hardened Shoot Cluster] Improve rule 1003 

- docs/rulesets/security-hardened-shoot-cluster/ruleset.md
- docs/rulesets/security-hardened-shoot-cluster/security-hardened-shoot-cluster-v0.2.1.yaml
- pkg/provider/garden/ruleset/securityhardenedshoot/rules/1001.go
- pkg/provider/garden/ruleset/securityhardenedshoot/rules/1001_test.go
- pkg/provider/garden/ruleset/securityhardenedshoot/rules/1002.go
- pkg/provider/garden/ruleset/securityhardenedshoot/rules/1002_test.go
This PR changes the severity of rules `1001` and `1002` from the `security-hardened-shoot-cluster` ruleset for provider `garden` from `HIGH` severity to `MEDIUM`.
Fixes #
```other user
Rule `1001` from the `security-hardened-shoot-cluster` ruleset for provider `garden` now has it's severity downgraded from `HIGH` to `MEDIUM`, starting from version `v0.2.1`.
```
```other user
Rule `1002` from the `security-hardened-shoot-cluster` ruleset for provider `garden` now has it's severity downgraded from `HIGH` to `MEDIUM`, starting from version `v0.2.1`.
```
> Change severity for rules 1001 & 1002 from shsc

- docs/usage/disa-k8s-stig-shoot.md
- docs/usage/security-hardened-k8s-shoot.md
- example/config/gardener.yaml
- example/guides/disa-k8s-stig-shoot.yaml
- example/guides/security-hardened-k8s-shoot.yaml
This PR improves example diki configs by updating justifications messages and using `< >` to note places the user needs to configure.
This PR also adds code snippets to the usage docs.
Fixes #
/cc @n-boshnakov 
```feature user
NONE
```
> Improve example diki configs and usage docs

- README.md
- docs/providers/gardener.md
- docs/providers/managedk8s.md
- docs/providers/virtualgarden.md
- example/config/gardener.yaml
- example/config/managedk8s.yaml
- example/config/virtualgarden.yaml
- example/guides/disa-k8s-stig-shoot.yaml
- hack/run.sh
- pkg/provider/gardener/ruleset/disak8sstig/ruleset.go
- pkg/provider/gardener/ruleset/disak8sstig/v2r3_ruleset.go
- pkg/provider/managedk8s/ruleset/disak8sstig/ruleset.go
- pkg/provider/managedk8s/ruleset/disak8sstig/v2r3_ruleset.go
- pkg/provider/virtualgarden/ruleset/disak8sstig/ruleset.go
- pkg/provider/virtualgarden/ruleset/disak8sstig/v2r3_ruleset.go
This PR adds support for the latest version of DISA K8s STIG `v2r3` and drops support for version `v2r1`.
Fixes #479
```feature user
Diki now supports DISA Kubernetes STIG version `v2r3`
```
```breaking user
Diki no longer supports DISA Kubernetes STIG version `v2r1`
```
> [DISA K8s STIG] Add support for version v2r3

- pkg/internal/utils/utils.go
- pkg/internal/utils/utils_test.go
- pkg/shared/ruleset/disak8sstig/rules/242459.go
- pkg/shared/ruleset/disak8sstig/rules/242459_test.go
This PR changes the implementation of DISA K8s STIG rule 242459 to check etcd files for `644` permissions or more restrictive, as stated in [the rule](https://stigviewer.com/stigs/kubernetes/2024-08-22/finding/V-242459). Files in `/etcd/data` directory are expected to have a maximum of `600` permissions, as they should not be accessible by `other` group and require write permissions.
`600` permissions are the minimal required for files in `/etcd/data` since the `etcd` creates and manages these files.
`640` permissions are still being enforced for all `.key` & `.pem` files via diki's implementation of [rule 242467](https://stigviewer.com/stigs/kubernetes/2024-08-22/finding/V-242467).
`644` permissions should be good enough for the general case, files …
> [DISA K8s STIG] Refactor rule 242459

- pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2000.go
- pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2000_test.go
Rule 2000 of the `Security Hardened Kubernetes Cluster` ruleset checks to see if unnecessary pod traffic is explicitly disabled for a specific namespace. If a `default-allow` NetworkPolicy is configured, all other NetworkPolicy rules are overwritten by it.
Example `default-allow` NetworkPolicy:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
name: default-allow
spec:
podSelector: {}
ingress:
- {}
egress:
- {}
policyTypes:
- Ingress
- Egress
```
The modification checks specifically for this type of NetworkPolicy and specifies it in the Failed `CheckResult` Target.
Fixes #439 
NONE
```feature user
[Security Hardened Kubernetes Cluster Ruleset] …
```
> [Security Hardened Kubernetes Cluster] Modify Rule 2000 to check for a `default-allow` NetworkPolicy

- pkg/provider/gardener/ruleset/disak8sstig/v2r2_ruleset.go
- pkg/provider/gardener/ruleset/disak8sstig/v2r3_ruleset.go
- pkg/provider/managedk8s/ruleset/disak8sstig/v2r2_ruleset.go
- pkg/provider/managedk8s/ruleset/disak8sstig/v2r3_ruleset.go
- pkg/provider/virtualgarden/ruleset/disak8sstig/v2r2_ruleset.go
- pkg/provider/virtualgarden/ruleset/disak8sstig/v2r3_ruleset.go
- pkg/shared/ruleset/disak8sstig/retryerrors/retryerrors.go
- pkg/shared/ruleset/disak8sstig/retryerrors/retryerrors_test.go
This PR adds retry on not found objects by `nerdctl`. In most cases these objects are the IDs of pod containers, which may may no longer exist when we try to find them with `nerdctl`
Fixes #
```feature user
NONE
```
> Retry rules on not found object by `nerdctl`

- pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2001.go
- pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2001_test.go
- pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2003.go
- pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2003_test.go
- pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2008.go
- pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2008_test.go
This PR skips the check of privileged diki pods from rules they violate.
Fixes #
```bugfix user
A bug causing diki pods to appear in `Failed` rule checks has been fixed.
```
> Skip diki privileged pods from checks

- pkg/provider/gardener/ruleset/disak8sstig/rules/242442.go
- pkg/provider/gardener/ruleset/disak8sstig/rules/242442_test.go
- pkg/provider/managedk8s/ruleset/disak8sstig/rules/242442.go
- pkg/provider/managedk8s/ruleset/disak8sstig/rules/242442_test.go
- pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2005.go
- pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2005_test.go
- pkg/provider/virtualgarden/ruleset/disak8sstig/rules/242442.go
- pkg/provider/virtualgarden/ruleset/disak8sstig/rules/242442_test.go
In #492. it is reported that rules checking the `ImageID` return an `Errored` result, when a Container has an unknown status or is not running. 
While this is an expected behavior, it should be noted that `Warning` would be a more suitable checkResult status for these cases, since it implies ambiguity in the evaluated target, while `Errored` [implies a runtime failure to evaluate the target](https://github.com/gardener/diki/blob/a59535d5f7123d3440d379b854dde70b7961b6f3/pkg/rule/rule.go#L150-L153).
This PR changes the checkResult status from `Errored` to `Warning` for these cases.
Fixes #492
NONE
```other user
Rule 2005 of the Security Hardened Kubernetes Cluster …
```
> Refactor the Status of checkResults that imply an empty ImageID in Rules 2005 (Security Hardened Kubernetes) and 242442 (DISA STIG)

- example/config/garden.yaml
- example/config/gardener.yaml
- example/config/virtualgarden.yaml
- pkg/provider/garden/ruleset/securityhardenedshoot/rules/2000.go
- pkg/provider/garden/ruleset/securityhardenedshoot/rules/2000_test.go
- pkg/provider/garden/ruleset/securityhardenedshoot/rules/options.go
- pkg/provider/garden/ruleset/securityhardenedshoot/v01_ruleset.go
- pkg/provider/garden/ruleset/securityhardenedshoot/v02_ruleset.go
- pkg/provider/gardener/ruleset/disak8sstig/rules/options.go
- pkg/provider/gardener/ruleset/disak8sstig/v2r2_ruleset.go
- pkg/provider/gardener/ruleset/disak8sstig/v2r3_ruleset.go
- pkg/provider/virtualgarden/ruleset/disak8sstig/rules/options.go
- pkg/provider/virtualgarden/ruleset/disak8sstig/v2r2_ruleset.go
- pkg/provider/virtualgarden/ruleset/disak8sstig/v2r3_ruleset.go
- pkg/shared/ruleset/disak8sstig/rules/242390.go
- pkg/shared/ruleset/disak8sstig/rules/242390_test.go
Diki supports two rules that check for enabled anonymous authentication to the `kube-apiserver`:
- Rule 242390 of the `DISA STIG` ruleset
- Rule 2000 of the `Security Hardened Shoot Cluster` ruleset
Currently, these rules check the `kube-apiserver`'s `AuthenticationConfiguration`. If the the `.anonymous.enabled` field is set to true, Diki returns a `Failed` checkResult, regardless of whether condition endpoints are present in the configuration. In order to perform more precise checks, `ruleOptions` should be introduced to allow anonymous authentication to specific endpoints.
For both rules, this PR configures `ruleOptions`, which represent a list of allowed endpoints. If the `kube-apiserver`'s `AuthenticationConfiguration` contains a subset of the …
> Configure rule options for rules 2000 of the Security Hardened Shoot Cluster ruleset and 242390 of the DISA STIG ruleset

- .github/workflows/build.yaml
The currently built diki binaries are broken for linux-arm systems:
``` bash
$ ./diki-linux-arm64
bash: ./diki-linux-arm64: cannot execute: required file not found
```
The runner version `ubuntu-24.04-arm` seems to be the cause.
This PR reverts the version to `ubuntu-latest`, which would build a working binary
Fixes #
```feature user
NONE
```
> Use `ubuntu-latest` for all diki binaries

- .github/workflows/build.yaml
(cherry picked from commit fb54189957b7ea8e184d8ff8cbddc56b4e5d8b88)
Fixes #
```user bugfix
Reverted to using `ubuntu-latest` for all diki executables builds in workflows, since the linux-arm64 binary was broken with the new `ubuntu-24.04-arm` runner.
```
> Use ubuntu-latest for all diki builds (#569)

- .github/workflows/build.yaml
Fixes #
```other operator
Use `ubuntu-24.04-arm` runner for diki executables builds in workflows.
```
```bugfix operator
Disable CGO for diki executables builds in workflows. This was causing the diki binaries to error in containers using alpine images.
```
> Disable CGO on diki build workflow

- pkg/provider/builder/garden.go
- pkg/provider/builder/gardener.go
- pkg/provider/builder/managedk8s.go
- pkg/provider/builder/virtualgarden.go
- pkg/provider/garden/ruleset/securityhardenedshoot/ruleset.go
- pkg/provider/gardener/ruleset/disak8sstig/ruleset.go
- pkg/provider/managedk8s/ruleset/disak8sstig/ruleset.go
- pkg/provider/managedk8s/ruleset/securityhardenedk8s/ruleset.go
- pkg/provider/virtualgarden/ruleset/disak8sstig/ruleset.go
This PR adds a reference to the `diki show` command in the cases when an error is returned due to an incorrectly composed configuration file.
Fixes #361 
```other user
Diki now refers to the `diki show` command when an error caused by a file misconfiguration occurs.
```
> Refactor `unknown provider|ruleset|ruleset version` error messages to refer the user to the diki show command

- pkg/shared/ruleset/disak8sstig/rules/242390.go
- pkg/shared/ruleset/disak8sstig/rules/242390_test.go
Improved rule 242390 from DISA K8s STIG to always return endpoints with anonymous authentication enabled in check results.
Fixes #
```bugfix user
A bug causing Rule 242390 from DISA K8s STIG to not return endpoints with anonymous authentication enabled in check results when options for the rule were not configured has been fixed.
```
> [DISA K8s STIG] List endpoints when options are missing for rule 242390

- pkg/provider/managedk8s/ruleset/disak8sstig/v2r2_ruleset.go
- pkg/provider/managedk8s/ruleset/disak8sstig/v2r3_ruleset.go
**How to categorize this PR?**
/kind bug
This PR improves the DISA K8s STIG ruleset for the `managedk8s` provider to no longer error when CA cannot be found from the provided kubeconfig. Now if a CA is not provided the rules will run.
Fixes #599
```bugfix user
A bug causing the DISA K8s STIG ruleset for the `managedk8s` provider to error when the provided kubeconfig does not contain CA Data has been fixed.
```
```bugfix user
A bug causing the DISA K8s STIG rule 242390 for the `managedk8s` provider to error when the provided kubeconfig uses a CA file or has insecure skip tls verify has been fixed.
```
> Do not error when CA files are missing
