gardener/diki

LICENSE

This PR copies the apache license so that it can be recognized in sites as https://pkg.go.dev/
Fixes #
```feature user
NONE
```

replace symlink with copy of the apache license

---

.dockerignore
Dockerfile
cmd/diki/app/app.go
hack/get-build-ld-flags.sh

Fixes #14 
```feature user
It is now possible to print version details about the diki binary by running `diki version`.
```

add version command to diki

---

Makefile
hack/build.sh

Fixes #15
```feature developer
It is now possible to build `diki` binaries for different platforms by running `make build`.
```

Build recipes

---

pkg/provider/gardener/ruleset/disak8sstig/v1r10/242397.go
pkg/provider/gardener/ruleset/disak8sstig/v1r10/242397_test.go

Part of #9 
```feature user
NONE
```

[Kubernetes STIG v1r10] Update 242397 rule

---

pkg/provider/gardener/ruleset/disak8sstig/v1r10/242391.go
pkg/provider/gardener/ruleset/disak8sstig/v1r10/242391_test.go
pkg/provider/gardener/ruleset/disak8sstig/v1r10/242392.go
pkg/provider/gardener/ruleset/disak8sstig/v1r10/242392_test.go

Part of https://github.com/gardener/diki/issues/9
```feature user
NONE
```

[Kubernetes STIG v1r10] Update 242391 and 242392 rules

---

pkg/provider/gardener/ruleset/disak8sstig/v1r10/245543.go
pkg/provider/gardener/ruleset/disak8sstig/v1r10/245544.go

Part of #9
```feature user
```

[Kubernetes STIG v1r10] Change severity of 245543 and 245544 rules

---

pkg/provider/gardener/ruleset/disak8sstig/v1r10/242424.go
pkg/provider/gardener/ruleset/disak8sstig/v1r10/242425.go
pkg/provider/gardener/ruleset/disak8sstig/v1r10/node_files_permissions_and_owner.go

Fixes #
```feature user
NONE
```

Add link to certificate-rotation documentation

---

pkg/provider/gardener/ruleset/disak8sstig/v1r10/242466.go
pkg/provider/gardener/ruleset/disak8sstig/v1r10/242466_test.go
pkg/provider/gardener/ruleset/disak8sstig/v1r10/242467.go
pkg/provider/gardener/ruleset/disak8sstig/v1r10/242467_test.go

Fixes #
```feature user
NONE
```

Improve skip message for 242466 and 242467 rule

---

pkg/provider/gardener/ruleset/disak8sstig/v1r10/242424_test.go
pkg/provider/gardener/ruleset/disak8sstig/v1r10/242425_test.go
pkg/provider/gardener/ruleset/disak8sstig/v1r10/node_files_permissions_and_owner.go
pkg/provider/gardener/ruleset/disak8sstig/v1r10/node_files_permissions_and_owner_test.go
pkg/provider/gardener/ruleset/disak8sstig/v1r10/pod_files_permissions_and_owner_test.go

Part of #9 
```feature user
NONE
```

[Kubernetes STIG v1r10] Dynamically find `kubelet` files

---

Dockerfile

Fixes #
```other dependency
Update go version to `1.21.1`.
```

Update go version to `1.21.1`

---

docs/rulesets/disa-k8s-stig.md

Fixes #
```feature user
NONE
```

doc: replace a broken link to cyber.trackr.live

---

.github/workflows/upload-diki-binaries.yaml
Dockerfile

Fixes #
```other dependency
Diki is now built using go version `1.21.2`.
```

update go to version 1.21.2

---

.github/workflows/upload-diki-binaries.yaml
Dockerfile

Fixes #
```other dependency
Diki is now built using go version `1.21.3`.
```

Update go to version 1.21.3

---

pkg/provider/gardener/ruleset/disak8sstig/v1r10/245541.go
pkg/provider/gardener/ruleset/disak8sstig/v1r8/245541.go

Fixes #
```feature user
NONE
```

Fix DISA Kubernetes STIGs`245541` rule name

---

pkg/provider/virtualgarden/ruleset/disak8sstig/v1r11_ruleset.go

Fixes #
```feature user
NONE
```

[DISA K8s STIG] Skip 242393, 242394, 242395, 242396 and 242397

---

pkg/provider/gardener/ruleset/disak8sstig/v1r11/242415.go

Fixes #
```feature user
NONE
```

[DISA K8s STIG] Fix target of rule 242415

---

pkg/provider/gardener/ruleset/disak8sstig/v1r11_ruleset.go
pkg/provider/virtualgarden/ruleset/disak8sstig/v1r11_ruleset.go
pkg/shared/ruleset/disak8sstig/v1r11/242459.go
pkg/shared/ruleset/disak8sstig/v1r11/242467.go
pkg/shared/ruleset/disak8sstig/v1r11/242467_test.go
pkg/shared/ruleset/disak8sstig/v1r11/v1r11_suite_test.go

This PR implements DISA K8s STIGs rule 242467
Fixes #
```feature user
NONE
```

[DISA K8s STIG] Implement rule 242467

---

pkg/provider/gardener/ruleset/disak8sstig/v1r11_ruleset.go
pkg/provider/virtualgarden/ruleset/disak8sstig/v1r11_ruleset.go
pkg/shared/ruleset/disak8sstig/v1r11/242466.go
pkg/shared/ruleset/disak8sstig/v1r11/242466_test.go

This PR implements DISA K8s STIGs rule 242466
Fixes #
```feature user
NONE
```

[DISA K8s STIG] Implement rule 242466

---

example/config/gardener.yaml
example/config/virtualgarden.yaml
pkg/internal/utils/utils.go
pkg/provider/gardener/ruleset/disak8sstig/v1r11_ruleset.go
pkg/provider/virtualgarden/ruleset/disak8sstig/v1r11/options.go
pkg/provider/virtualgarden/ruleset/disak8sstig/v1r11_ruleset.go
pkg/shared/ruleset/disak8sstig/v1r11/242451.go
pkg/shared/ruleset/disak8sstig/v1r11/242451_test.go
pkg/shared/ruleset/disak8sstig/v1r11/242467.go

This PR implement DISA K8s STIGs rule 242451
Part of https://github.com/gardener/diki/issues/82
```feature user
NONE
```

[DISA K8s STIG] Implement rule 242451

---

.github/workflows/upload-diki-binaries.yaml

Update go version for building diki go binaries

---

pkg/provider/gardener/ruleset/disak8sstig/v1r11/242387.go
pkg/provider/gardener/ruleset/disak8sstig/v1r11/242391.go
pkg/provider/gardener/ruleset/disak8sstig/v1r11/242392.go
pkg/provider/gardener/ruleset/disak8sstig/v1r11/242393.go
pkg/provider/gardener/ruleset/disak8sstig/v1r11/242394.go
pkg/provider/gardener/ruleset/disak8sstig/v1r11/242397.go
pkg/provider/gardener/ruleset/disak8sstig/v1r11/242399.go
pkg/provider/gardener/ruleset/disak8sstig/v1r11/242404.go
pkg/provider/gardener/ruleset/disak8sstig/v1r11/242420.go
pkg/provider/gardener/ruleset/disak8sstig/v1r11/242424.go
pkg/provider/gardener/ruleset/disak8sstig/v1r11/242425.go
pkg/provider/gardener/ruleset/disak8sstig/v1r11/242434.go
pkg/provider/gardener/ruleset/disak8sstig/v1r11/245541.go
pkg/provider/gardener/ruleset/disak8sstig/v1r11/254801.go
pkg/provider/gardener/ruleset/disak8sstig/v1r11/node_files_permissions_and_owner.go
pkg/provider/gardener/ruleset/disak8sstig/v1r11/pod_files_permissions_and_owner.go
pkg/shared/ruleset/disak8sstig/v1r11/242445.go
pkg/shared/ruleset/disak8sstig/v1r11/242446.go
pkg/shared/ruleset/disak8sstig/v1r11/242451.go
pkg/shared/ruleset/disak8sstig/v1r11/242459.go
pkg/shared/ruleset/disak8sstig/v1r11/242460.go
pkg/shared/ruleset/disak8sstig/v1r11/242466.go
pkg/shared/ruleset/disak8sstig/v1r11/242467.go

Fixes #
```feature user
NONE
```

Use WithOptionalTag()

---

pkg/provider/managedk8s/ruleset/disak8sstig/v1r11/242415.go
pkg/provider/managedk8s/ruleset/disak8sstig/v1r11/242415_test.go
pkg/provider/managedk8s/ruleset/disak8sstig/v1r11_ruleset.go

Fixes #
```feature user
NONE
```

Remove logger from rule 242415

---

example/config/managedk8s.yaml
pkg/provider/gardener/ruleset/disak8sstig/v1r11_ruleset.go
pkg/provider/managedk8s/ruleset/disak8sstig/v1r11/options.go
pkg/provider/managedk8s/ruleset/disak8sstig/v1r11_ruleset.go
pkg/shared/ruleset/disak8sstig/v1r11/242406.go
pkg/shared/ruleset/disak8sstig/v1r11/242406_test.go
pkg/shared/ruleset/disak8sstig/v1r11/242407.go
pkg/shared/ruleset/disak8sstig/v1r11/242407_test.go

This PR implement DISA K8s STIGs rule `242407`
Part of #82 
```feature user
NONE
```

[DISA K8s STIG] Implement rule 242407

---

example/config/managedk8s.yaml
pkg/provider/gardener/ruleset/disak8sstig/v1r11_ruleset.go
pkg/provider/managedk8s/ruleset/disak8sstig/v1r11/options.go
pkg/provider/managedk8s/ruleset/disak8sstig/v1r11_ruleset.go
pkg/shared/ruleset/disak8sstig/v1r11/242447_test.go
pkg/shared/ruleset/disak8sstig/v1r11/242448.go
pkg/shared/ruleset/disak8sstig/v1r11/242448_test.go

This PR implements shared DISA K8s STIGs rule 242448.
Part of #67 
```feature user
NONE
```

[DISA K8s STIG] Implement rule 242448

---

example/config/managedk8s.yaml
pkg/provider/gardener/ruleset/disak8sstig/v1r11_ruleset.go
pkg/provider/managedk8s/ruleset/disak8sstig/v1r11/options.go
pkg/provider/managedk8s/ruleset/disak8sstig/v1r11_ruleset.go
pkg/shared/ruleset/disak8sstig/v1r11/242453.go
pkg/shared/ruleset/disak8sstig/v1r11/242453_test.go

This PR implement DISA K8s STIGs rule 242453
Part of https://github.com/gardener/diki/issues/82
```feature user
NONE
```

[DISA K8s STIG] Implement rule 242453

---

example/config/managedk8s.yaml
pkg/provider/gardener/ruleset/disak8sstig/v1r11_ruleset.go
pkg/provider/managedk8s/ruleset/disak8sstig/v1r11/options.go
pkg/provider/managedk8s/ruleset/disak8sstig/v1r11_ruleset.go
pkg/shared/ruleset/disak8sstig/v1r11/242447.go
pkg/shared/ruleset/disak8sstig/v1r11/242448.go
pkg/shared/ruleset/disak8sstig/v1r11/242452.go
pkg/shared/ruleset/disak8sstig/v1r11/242452_test.go

This PR implement DISA K8s STIGs rule 242452
Part of https://github.com/gardener/diki/issues/82
```feature user
NONE
```

[DISA K8s STIG] Implement rule 242452

---

example/config/managedk8s.yaml
pkg/provider/gardener/ruleset/disak8sstig/v1r11_ruleset.go
pkg/provider/managedk8s/ruleset/disak8sstig/v1r11/options.go
pkg/provider/managedk8s/ruleset/disak8sstig/v1r11_ruleset.go
pkg/shared/ruleset/disak8sstig/v1r11/242450.go
pkg/shared/ruleset/disak8sstig/v1r11/242450_test.go

This PR implements shared DISA K8s STIGs rule 242450.
Part of #67
```feature user
NONE
```

[DISA K8s STIG] Implement shared rule 242450

---

example/config/managedk8s.yaml
pkg/kubernetes/utils/utils.go
pkg/kubernetes/utils/utils_test.go
pkg/provider/gardener/ruleset/disak8sstig/v1r11_ruleset.go
pkg/provider/managedk8s/ruleset/disak8sstig/v1r11/options.go
pkg/provider/managedk8s/ruleset/disak8sstig/v1r11_ruleset.go
pkg/shared/ruleset/disak8sstig/v1r11/242383.go
pkg/shared/ruleset/disak8sstig/v1r11/242383_test.go
pkg/shared/ruleset/disak8sstig/v1r11/242417.go
pkg/shared/ruleset/disak8sstig/v1r11/242417_test.go

This PR implements shared DISA K8s STIGs rule 242383.
Part of #67 
```feature user
NONE
```

[DISA K8s STIG] Implement shared rule 242383

---

Dockerfile

Update nerdctl version to 1.7.4
Fixes #
```feature user
NONE
```

Update nerdctl version to 1.7.4

---

.github/renovate.json5

Fixes #
```feature user
NONE
```

Add go mod tidy to renovate PRs

---

.github/renovate.json5

Fixes #
```feature user
NONE
```

Renovate update docker github manifests

---

docs/usage/partial-disa-k8s-stig-shoot.md

This PR cleans up the "Run Partial DISA K8s STIGs Ruleset Against a Gardener Shoot Cluster" topic.
Fixes #
```doc developer
NONE
```

Proofread the "Run Partial DISA K8s STIGs Ruleset Against a Gardener Shoot Cluster" topic

---

.reuse/dep5

Fixes #
```feature user
NONE
```

Remove ci/hack/* files from dep5

---

pkg/provider/gardener/ruleset/disak8sstig/v1r11_ruleset.go

Fixes #
```bugfix user
A bug causing rule 242452 for gardener provider to check seed nodes instead of shoot nodes was fixed.
```

[DISA K8s STIG] Fix rule 242452 for gardener provider

---

pkg/report/merged_report.go
pkg/report/report.go

Fixes #
```other user
Rules in html reports are now sorted by rule ID.
```

Sort rules by ID in html reports

---

Dockerfile

Minimize container image to reduce attack surface.
Fixes #210
```other operator
diki-ops container image now includes only needed binaries.
```

Minimise `diki-ops` container

---

pkg/shared/provider/provider.go
pkg/shared/ruleset/ruleset.go

Fixes #
```other user
NONE
```

Use statics messages for logs

---

docs/usage/partial-disa-k8s-stig-shoot.md

Fixes #
```feature user
NONE
```

[Docu] Fix diki commands in partial DISA K8s STIG guide

---

example/config/gardener.yaml
example/config/managedk8s.yaml
example/config/virtualgarden.yaml

This PR add example config for skipping rules for all example configs
Fixes #
```feature user
NONE
```

Add skip rule example

---

pkg/report/templates/html/merged_report.html
pkg/report/templates/html/report.html

Fixes #
```feature user
NONE
```

Remove unnecessary new lines from diki reports

---

pkg/provider/managedk8s/ruleset/disak8sstig/v1r11_ruleset.go
pkg/provider/virtualgarden/ruleset/disak8sstig/v1r11_ruleset.go

Fixes #
```feature user
NONE
```

Fix rule names typos

---

pkg/kubernetes/pod/pod.go

This PR improves `SimplePodExecutor`'s `Execute()` to retry every 2 seconds for 30 seconds if the command execution was timed out or there as a server error.
Part of #253 
```other user
`SimplePodExecutor` now retries command timeouts and server errors.
```

SimplePodExecutor now retries command timeout and peer errors

---

pkg/provider/gardener/ruleset/disak8sstig/v1r11/242442.go
pkg/provider/gardener/ruleset/disak8sstig/v1r11/242442_test.go

This PR improves `disa-kubernetes-stig` ruleset rule `242442` for `gardener` provider by making it check Pod's images per namespace.
The change brings the rules closer to the actual rule description of the stig found [here](https://www.stigviewer.com/stig/kubernetes/2023-08-29/finding/V-242442). In there rule it is wanted for old components to be removed when their updated versions have been installed. It is reasonable to assume that if a component is being updated it will happen the updated version will be in the same namespace as the old component
Fixes #
```other user
Improved `disa-kubernetes-stig` ruleset rule `242442` for `gardener` provider to check pod …
```

[DISA K8s STIG] Rule 242442 for gardener provider check image per namespace

---

docs/usage/partial-disa-k8s-stig-shoot.md

This PR adds a description to the "Run Partial DISA K8s STIGs Ruleset Against a Gardener Shoot Cluster" topic.
Fixes #
```doc developer
NONE
```

Added description to "Run Partial DISA K8s STIGs Ruleset Against a Gardener Shoot Cluster" topic

---

example/guides/partial-disa-k8s-stig-shoot.yaml

Fixes #
```feature user
NONE
```

Improve partial disa k8s guide example

---

pkg/kubernetes/utils/utils.go
pkg/report/merged_report.go
pkg/report/render.go
pkg/report/report.go

Fixes #
```feature user
NONE
```

Simplify some code

---

docs/usage/partial-disa-k8s-stig-shoot.md

This PR fixes broken links in the documentation.
Fixes #
```doc developer
NONE
```

Fixed broken links - 2024.10

---

pkg/internal/utils/utils.go
pkg/kubernetes/utils/utils.go

This PR adds additional comment suggestions that remained unaddressed from PR #325 
```
NONE
```

Add additional comment suggestions to the GetContainer util methods

---

docs/rulesets/security-hardened-shoot-cluster/security-hardened-shoot-cluster-v0.1.0.yaml
pkg/provider/garden/ruleset/securityhardenedshoot/rules/2003.go
pkg/provider/garden/ruleset/securityhardenedshoot/rules/2003_test.go

Fixes #
```feature user
NONE
```

Add severity to Security Hardened Shoot Cluster rules

---

.golangci.yaml
docs/rulesets/security-hardened-k8s/ruleset.md
docs/rulesets/security-hardened-k8s/security-hardened-k8s-v0.1.0.yaml
example/config/managedk8s.yaml
pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2008.go
pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2008_test.go
pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/doc.go
pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/options.go
pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/rules_suite_test.go
pkg/provider/managedk8s/ruleset/securityhardenedk8s/v01_ruleset.go

Part of #356 
```feature user
Implementation for rule `2008` from the `security-hardened-k8s` ruleset for provider `managedk8s`.
```

[Security Hardened Kubernetes Cluster] Rule 2008 implementation

---

example/config/managedk8s.yaml
pkg/kubernetes/utils/utils.go
pkg/kubernetes/utils/utils_test.go
pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2001.go
pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2001_test.go
pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2004.go
pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2004_test.go
pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2006.go
pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2006_test.go
pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/options.go
pkg/provider/managedk8s/ruleset/securityhardenedk8s/v01_ruleset.go
pkg/shared/kubernetes/option/options.go
pkg/shared/kubernetes/option/options_test.go

Part of https://github.com/gardener/diki/issues/356
```feature user
Implementation for rule `2006` from the `security-hardened-k8s` ruleset for provider `managedk8s`.
```

[Security Hardened Kubernetes Cluster] Rule 2006 implementation

---

docs/usage/disa-k8s-stig-shoot.md

Fixes #
```feature user
NONE
```

Rephrase parts of the disa k8s stig shoot guide

---

pkg/kubernetes/utils/utils.go
pkg/kubernetes/utils/utils_test.go
pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2002.go
pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2002_test.go
pkg/provider/managedk8s/ruleset/securityhardenedk8s/v01_ruleset.go

Part #356 
```feature user
Implementation for rule `2002` from the `security-hardened-k8s` ruleset for provider `managedk8s`.
```

[Security Hardened Kubernetes Cluster] Rule 2002 implementation 

---

example/config/managedk8s.yaml
pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2006.go
pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2006_test.go
pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2007.go
pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2007_test.go
pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/options.go
pkg/provider/managedk8s/ruleset/securityhardenedk8s/v01_ruleset.go

Part of #356 
```feature user
Implementation for rule `2007` from the `security-hardened-k8s` ruleset for provider `managedk8s`.
```

[Security Hardened Kubernetes Cluster] Rule 2007 implementation

---

example/config/managedk8s.yaml
pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2003.go
pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2003_test.go
pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/options.go
pkg/provider/managedk8s/ruleset/securityhardenedk8s/v01_ruleset.go

Part of #356 
```feature user
Implementation for rule `2003` from the `security-hardened-k8s` ruleset for provider `managedk8s`.
```

[Security Hardened Kubernetes Cluster] Rule 2003 implementation

---

docs/rulesets/security-hardened-shoot-cluster/ruleset.md

Fixes #
```feature user
NONE
```

Reference correct rule in Security Hardened Shoot cluter guide

---

docs/rulesets/security-hardened-k8s/ruleset.md
docs/rulesets/security-hardened-shoot-cluster/ruleset.md

This PR adds rule IDs in ruleset documentation files for easier targeting of rules.
Fixes #
```feature user
NONE
```

Add rule IDs in ruleset documentation files

---

pkg/kubernetes/pod/pod.go

With kubernetes `v1.31` [Streaming Transitions from SPDY to WebSockets](https://kubernetes.io/blog/2024/08/20/websockets-transition/). This PR updates the Execute() method of `SimplePodExecutor` to use the WebSocket executor as primary and the spdy as fallback similar to kubectl.
This change is needed to work with changes to gardener: https://github.com/gardener/gardener/pull/11085
Fixes #
```feature user
NONE
```

Use websocket executor as primary

---

docs/providers/garden.md
docs/rulesets/security-hardened-shoot-cluster/security-hardened-shoot-cluster-v0.2.0.yaml
example/guides/disa-k8s-stig-shoot.yaml

Release version `v0.2.0` of Security Hardened Shoot Cluster ruleset.
Fixes #
```feature user
Release version `v0.2.0` of Security Hardened Shoot Cluster Guide.
```

Release and use v0.2.0 of Security Hardened Shoot Cluster

---

pkg/provider/garden/ruleset/securityhardenedshoot/v02_ruleset.go

This PR updates the amount of rules present in the Security Hardened Shoot Cluster
None
cc @AleksandarSavchev 
```feature user
```

Update Security Hardened Shoot Cluster rule count

---

README.md

This PR adds `Install using Package Managers` section in `README.md` file.
Fixes #
```feature user
NONE
```

Add Install using Package Managers docu

---

README.md
cmd/diki/app/app.go

Improving spelling
No fixes
```feature user
NONE
```

fix spelling in diki app

---

pkg/provider/gardener/ruleset/disak8sstig/rules/242377.go
pkg/provider/gardener/ruleset/disak8sstig/rules/242377_test.go
pkg/provider/gardener/ruleset/disak8sstig/rules/242400.go
pkg/provider/gardener/ruleset/disak8sstig/rules/242400_test.go
pkg/provider/gardener/ruleset/disak8sstig/rules/242415.go
pkg/provider/gardener/ruleset/disak8sstig/rules/242415_test.go
pkg/provider/gardener/ruleset/disak8sstig/rules/242442.go
pkg/provider/gardener/ruleset/disak8sstig/rules/242442_test.go
pkg/provider/gardener/ruleset/disak8sstig/rules/242451.go
pkg/provider/gardener/ruleset/disak8sstig/rules/242451_test.go
pkg/provider/gardener/ruleset/disak8sstig/rules/242466.go
pkg/provider/gardener/ruleset/disak8sstig/rules/242466_test.go
pkg/provider/gardener/ruleset/disak8sstig/rules/242467.go
pkg/provider/gardener/ruleset/disak8sstig/rules/242467_test.go

This PR refactors checkResult targets of the DISA STIG rules that have specific implementations for the Gardener provider.
Part of #504 
```feature user
```

Refactor Targets for DISA STIG rules implemented for the Gardener Provider

---

Dockerfile

Fixes #
```feature user
NONE
```

Fix `as` casing to match `FROM` casing
